name: yalp_drift_storage
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.10.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  drift: ^2.30.0
  sqlite3_flutter_libs: ^0.5.41
  path_provider: ^2.1.3

  yalp_core:
    # path: ../yalp_core
    git: 
      url: https://github.com/bierbaumtim/yalp.git
      path: yalp_core

dev_dependencies:
  build_runner: ^2.10.4
  drift_dev: ^2.30.0

  lints: ^6.0.0
  test: ^1.28.0
